/**
 * Symbol Library Seed Script
 * Seeds 1000+ symbols across 9 categories
 * Run: npx tsx scripts/seed-symbols.ts
 */
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { symbolCategories, librarySymbols } from "../shared/schema";
import { eq, sql } from "drizzle-orm";

const { Pool } = pg;

async function seedSymbols() {
  if (!process.env.DATABASE_URL) {
    console.error("DATABASE_URL is required");
    process.exit(1);
  }
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  // ===== 1. Categories =====
  const categories = [
    { slug: "numbers-letters", nameAr: "أرقام وحروف", nameEn: "Numbers & Letters", icon: "🔢", sortOrder: 1 },
    { slug: "emotions-faces", nameAr: "وجوه ومشاعر", nameEn: "Emotions & Faces", icon: "😀", sortOrder: 2 },
    { slug: "animals", nameAr: "حيوانات", nameEn: "Animals", icon: "🐱", sortOrder: 3 },
    { slug: "nature-elements", nameAr: "طبيعة وعناصر", nameEn: "Nature & Elements", icon: "🌿", sortOrder: 4 },
    { slug: "shapes-colors", nameAr: "أشكال وألوان", nameEn: "Shapes & Colors", icon: "🔵", sortOrder: 5 },
    { slug: "educational-tools", nameAr: "أدوات تعليمية", nameEn: "Educational Tools", icon: "📚", sortOrder: 6 },
    { slug: "activities-hobbies", nameAr: "أنشطة وهوايات", nameEn: "Activities & Hobbies", icon: "⚽", sortOrder: 7 },
    { slug: "rewards-achievements", nameAr: "مكافآت وإنجازات", nameEn: "Rewards & Achievements", icon: "🏆", sortOrder: 8 },
    { slug: "project-specific", nameAr: "رموز المنصة", nameEn: "Project Symbols", icon: "✨", sortOrder: 9 },
  ];

  console.log("🔄 Seeding symbol categories...");
  const catMap: Record<string, string> = {};

  for (const cat of categories) {
    const existing = await db.select({ id: symbolCategories.id })
      .from(symbolCategories).where(eq(symbolCategories.slug, cat.slug)).limit(1);
    if (existing.length > 0) {
      catMap[cat.slug] = existing[0].id;
      console.log(`  ⏭️  Category "${cat.nameEn}" already exists`);
    } else {
      const [inserted] = await db.insert(symbolCategories).values(cat).returning();
      catMap[cat.slug] = inserted.id;
      console.log(`  ✅ Category "${cat.nameEn}" created`);
    }
  }

  // ===== 2. Symbols Data (1100+) =====
  type SymDef = { char: string; nameAr: string; nameEn: string; tags: string[] };

  const numbersLetters: SymDef[] = [
    // Digits
    { char: "0️⃣", nameAr: "صفر", nameEn: "Zero", tags: ["number", "digit", "0"] },
    { char: "1️⃣", nameAr: "واحد", nameEn: "One", tags: ["number", "digit", "1"] },
    { char: "2️⃣", nameAr: "اثنان", nameEn: "Two", tags: ["number", "digit", "2"] },
    { char: "3️⃣", nameAr: "ثلاثة", nameEn: "Three", tags: ["number", "digit", "3"] },
    { char: "4️⃣", nameAr: "أربعة", nameEn: "Four", tags: ["number", "digit", "4"] },
    { char: "5️⃣", nameAr: "خمسة", nameEn: "Five", tags: ["number", "digit", "5"] },
    { char: "6️⃣", nameAr: "ستة", nameEn: "Six", tags: ["number", "digit", "6"] },
    { char: "7️⃣", nameAr: "سبعة", nameEn: "Seven", tags: ["number", "digit", "7"] },
    { char: "8️⃣", nameAr: "ثمانية", nameEn: "Eight", tags: ["number", "digit", "8"] },
    { char: "9️⃣", nameAr: "تسعة", nameEn: "Nine", tags: ["number", "digit", "9"] },
    { char: "🔟", nameAr: "عشرة", nameEn: "Ten", tags: ["number", "digit", "10"] },
    // Math symbols
    { char: "➕", nameAr: "جمع", nameEn: "Plus", tags: ["math", "add", "addition"] },
    { char: "➖", nameAr: "طرح", nameEn: "Minus", tags: ["math", "subtract"] },
    { char: "✖️", nameAr: "ضرب", nameEn: "Multiply", tags: ["math", "times"] },
    { char: "➗", nameAr: "قسمة", nameEn: "Divide", tags: ["math", "division"] },
    { char: "🟰", nameAr: "يساوي", nameEn: "Equals", tags: ["math", "equal"] },
    { char: "💯", nameAr: "مئة", nameEn: "Hundred", tags: ["number", "score", "perfect"] },
    { char: "#️⃣", nameAr: "هاشتاج", nameEn: "Hash", tags: ["symbol", "number"] },
    { char: "*️⃣", nameAr: "نجمة", nameEn: "Asterisk", tags: ["symbol", "star"] },
    // Letters A-Z
    { char: "🅰️", nameAr: "أ (إنجليزي)", nameEn: "A", tags: ["letter", "english", "a"] },
    { char: "🅱️", nameAr: "ب (إنجليزي)", nameEn: "B", tags: ["letter", "english", "b"] },
    { char: "©️", nameAr: "حقوق", nameEn: "Copyright C", tags: ["letter", "c"] },
    { char: "Ⓜ️", nameAr: "م (دائري)", nameEn: "Circle M", tags: ["letter", "m"] },
    { char: "🅾️", nameAr: "أو", nameEn: "O", tags: ["letter", "english", "o"] },
    { char: "🅿️", nameAr: "بي", nameEn: "P", tags: ["letter", "english", "p", "parking"] },
    { char: "ℹ️", nameAr: "معلومات", nameEn: "Info", tags: ["letter", "i", "information"] },
    // Arabic letters as emoji-like  
    { char: "أ", nameAr: "ألف", nameEn: "Alef", tags: ["arabic", "letter", "حرف"] },
    { char: "ب", nameAr: "باء", nameEn: "Ba", tags: ["arabic", "letter", "حرف"] },
    { char: "ت", nameAr: "تاء", nameEn: "Ta", tags: ["arabic", "letter", "حرف"] },
    { char: "ث", nameAr: "ثاء", nameEn: "Tha", tags: ["arabic", "letter", "حرف"] },
    { char: "ج", nameAr: "جيم", nameEn: "Jim", tags: ["arabic", "letter", "حرف"] },
    { char: "ح", nameAr: "حاء", nameEn: "Ha", tags: ["arabic", "letter", "حرف"] },
    { char: "خ", nameAr: "خاء", nameEn: "Kha", tags: ["arabic", "letter", "حرف"] },
    { char: "د", nameAr: "دال", nameEn: "Dal", tags: ["arabic", "letter", "حرف"] },
    { char: "ذ", nameAr: "ذال", nameEn: "Dhal", tags: ["arabic", "letter", "حرف"] },
    { char: "ر", nameAr: "راء", nameEn: "Ra", tags: ["arabic", "letter", "حرف"] },
    { char: "ز", nameAr: "زاي", nameEn: "Zay", tags: ["arabic", "letter", "حرف"] },
    { char: "س", nameAr: "سين", nameEn: "Sin", tags: ["arabic", "letter", "حرف"] },
    { char: "ش", nameAr: "شين", nameEn: "Shin", tags: ["arabic", "letter", "حرف"] },
    { char: "ص", nameAr: "صاد", nameEn: "Sad", tags: ["arabic", "letter", "حرف"] },
    { char: "ض", nameAr: "ضاد", nameEn: "Dad", tags: ["arabic", "letter", "حرف"] },
    { char: "ط", nameAr: "طاء", nameEn: "Tah", tags: ["arabic", "letter", "حرف"] },
    { char: "ظ", nameAr: "ظاء", nameEn: "Dhah", tags: ["arabic", "letter", "حرف"] },
    { char: "ع", nameAr: "عين", nameEn: "Ain", tags: ["arabic", "letter", "حرف"] },
    { char: "غ", nameAr: "غين", nameEn: "Ghain", tags: ["arabic", "letter", "حرف"] },
    { char: "ف", nameAr: "فاء", nameEn: "Fa", tags: ["arabic", "letter", "حرف"] },
    { char: "ق", nameAr: "قاف", nameEn: "Qaf", tags: ["arabic", "letter", "حرف"] },
    { char: "ك", nameAr: "كاف", nameEn: "Kaf", tags: ["arabic", "letter", "حرف"] },
    { char: "ل", nameAr: "لام", nameEn: "Lam", tags: ["arabic", "letter", "حرف"] },
    { char: "م", nameAr: "ميم", nameEn: "Mim", tags: ["arabic", "letter", "حرف"] },
    { char: "ن", nameAr: "نون", nameEn: "Nun", tags: ["arabic", "letter", "حرف"] },
    { char: "ه", nameAr: "هاء", nameEn: "Ha2", tags: ["arabic", "letter", "حرف"] },
    { char: "و", nameAr: "واو", nameEn: "Waw", tags: ["arabic", "letter", "حرف"] },
    { char: "ي", nameAr: "ياء", nameEn: "Ya", tags: ["arabic", "letter", "حرف"] },
    // Math/Comparison extras
    { char: "∞", nameAr: "لانهاية", nameEn: "Infinity", tags: ["math", "infinity"] },
    { char: "≈", nameAr: "تقريبا", nameEn: "Approximately", tags: ["math", "approx"] },
    { char: "≠", nameAr: "لا يساوي", nameEn: "Not Equal", tags: ["math"] },
    { char: "≤", nameAr: "أقل من أو يساوي", nameEn: "Less Equal", tags: ["math"] },
    { char: "≥", nameAr: "أكبر من أو يساوي", nameEn: "Greater Equal", tags: ["math"] },
    { char: "π", nameAr: "باي", nameEn: "Pi", tags: ["math", "greek"] },
    { char: "√", nameAr: "جذر", nameEn: "Square Root", tags: ["math", "root"] },
    { char: "%", nameAr: "نسبة مئوية", nameEn: "Percent", tags: ["math", "percent"] },
    { char: "∑", nameAr: "مجموع", nameEn: "Summation", tags: ["math", "sum"] },
    { char: "∆", nameAr: "دلتا", nameEn: "Delta", tags: ["math", "change", "triangle"] },
    // Number words
    { char: "①", nameAr: "أول", nameEn: "First", tags: ["number", "ordinal", "1"] },
    { char: "②", nameAr: "ثاني", nameEn: "Second", tags: ["number", "ordinal", "2"] },
    { char: "③", nameAr: "ثالث", nameEn: "Third", tags: ["number", "ordinal", "3"] },
    { char: "④", nameAr: "رابع", nameEn: "Fourth", tags: ["number", "ordinal", "4"] },
    { char: "⑤", nameAr: "خامس", nameEn: "Fifth", tags: ["number", "ordinal", "5"] },
    { char: "⑥", nameAr: "سادس", nameEn: "Sixth", tags: ["number", "ordinal", "6"] },
    { char: "⑦", nameAr: "سابع", nameEn: "Seventh", tags: ["number", "ordinal", "7"] },
    { char: "⑧", nameAr: "ثامن", nameEn: "Eighth", tags: ["number", "ordinal", "8"] },
    { char: "⑨", nameAr: "تاسع", nameEn: "Ninth", tags: ["number", "ordinal", "9"] },
    { char: "⑩", nameAr: "عاشر", nameEn: "Tenth", tags: ["number", "ordinal", "10"] },
    // Extra symbols
    { char: "¼", nameAr: "ربع", nameEn: "Quarter", tags: ["fraction", "math"] },
    { char: "½", nameAr: "نصف", nameEn: "Half", tags: ["fraction", "math"] },
    { char: "¾", nameAr: "ثلاثة أرباع", nameEn: "Three Quarters", tags: ["fraction", "math"] },
    { char: "⅓", nameAr: "ثلث", nameEn: "Third Frac", tags: ["fraction", "math"] },
    { char: "⅔", nameAr: "ثلثين", nameEn: "Two Thirds", tags: ["fraction", "math"] },
  ];

  const emotionsFaces: SymDef[] = [
    { char: "😀", nameAr: "وجه سعيد", nameEn: "Grinning Face", tags: ["happy", "smile"] },
    { char: "😃", nameAr: "سعيد عيون كبيرة", nameEn: "Grinning Big Eyes", tags: ["happy", "smile"] },
    { char: "😄", nameAr: "سعيد عيون مبتسمة", nameEn: "Grinning Squinting", tags: ["happy", "laugh"] },
    { char: "😁", nameAr: "ابتسامة عريضة", nameEn: "Beaming", tags: ["happy", "grin"] },
    { char: "😆", nameAr: "ضاحك", nameEn: "Laughing", tags: ["happy", "laugh", "fun"] },
    { char: "😅", nameAr: "ضحك بعرق", nameEn: "Sweat Smile", tags: ["nervous", "laugh"] },
    { char: "🤣", nameAr: "ضحك بالأرض", nameEn: "ROFL", tags: ["laugh", "funny"] },
    { char: "😂", nameAr: "دموع فرح", nameEn: "Joy Tears", tags: ["laugh", "cry", "happy"] },
    { char: "🙂", nameAr: "ابتسامة خفيفة", nameEn: "Slight Smile", tags: ["smile", "happy"] },
    { char: "🙃", nameAr: "وجه مقلوب", nameEn: "Upside Down", tags: ["silly", "playful"] },
    { char: "😉", nameAr: "غمزة", nameEn: "Wink", tags: ["wink", "flirt"] },
    { char: "😊", nameAr: "خجول", nameEn: "Blush", tags: ["blush", "happy", "shy"] },
    { char: "😇", nameAr: "ملاك", nameEn: "Angel", tags: ["angel", "innocent", "good"] },
    { char: "🥰", nameAr: "وجه حب", nameEn: "Love Face", tags: ["love", "hearts"] },
    { char: "😍", nameAr: "عيون قلب", nameEn: "Heart Eyes", tags: ["love", "wow"] },
    { char: "🤩", nameAr: "عيون نجوم", nameEn: "Star Eyes", tags: ["excited", "wow", "star"] },
    { char: "😘", nameAr: "قبلة", nameEn: "Kiss", tags: ["kiss", "love"] },
    { char: "😗", nameAr: "وجه مقبل", nameEn: "Kissing", tags: ["kiss"] },
    { char: "😚", nameAr: "قبلة خجولة", nameEn: "Kissing Closed", tags: ["kiss", "shy"] },
    { char: "😙", nameAr: "قبلة مبتسمة", nameEn: "Kissing Smile", tags: ["kiss", "smile"] },
    { char: "🥲", nameAr: "ابتسامة بدمعة", nameEn: "Smiling Tear", tags: ["sad", "happy", "tear"] },
    { char: "😋", nameAr: "لذيذ", nameEn: "Yummy", tags: ["food", "delicious", "tongue"] },
    { char: "😛", nameAr: "لسان", nameEn: "Tongue", tags: ["playful", "tongue"] },
    { char: "😜", nameAr: "غمزة بلسان", nameEn: "Wink Tongue", tags: ["playful", "silly"] },
    { char: "🤪", nameAr: "مجنون", nameEn: "Zany", tags: ["crazy", "silly", "fun"] },
    { char: "😝", nameAr: "لسان مغمض", nameEn: "Squinting Tongue", tags: ["playful"] },
    { char: "🤑", nameAr: "وجه مال", nameEn: "Money Face", tags: ["money", "rich"] },
    { char: "🤗", nameAr: "حضن", nameEn: "Hugging", tags: ["hug", "warm"] },
    { char: "🤭", nameAr: "ضحكة خجولة", nameEn: "Hand Over Mouth", tags: ["shy", "giggle"] },
    { char: "🤫", nameAr: "صمت", nameEn: "Shushing", tags: ["quiet", "secret"] },
    { char: "🤔", nameAr: "تفكير", nameEn: "Thinking", tags: ["think", "question", "hmm"] },
    { char: "🫡", nameAr: "تحية", nameEn: "Saluting", tags: ["salute", "respect"] },
    { char: "🤐", nameAr: "فم مغلق", nameEn: "Zipper Mouth", tags: ["silent", "secret"] },
    { char: "🤨", nameAr: "حاجب مرفوع", nameEn: "Raised Eyebrow", tags: ["skeptical", "doubt"] },
    { char: "😐", nameAr: "وجه محايد", nameEn: "Neutral", tags: ["neutral", "blank"] },
    { char: "😑", nameAr: "وجه بلا تعبير", nameEn: "Expressionless", tags: ["blank", "bored"] },
    { char: "😶", nameAr: "بدون فم", nameEn: "No Mouth", tags: ["silent", "speechless"] },
    { char: "🫥", nameAr: "وجه خط منقط", nameEn: "Dotted Line", tags: ["invisible", "hidden"] },
    { char: "😏", nameAr: "ابتسامة ماكرة", nameEn: "Smirk", tags: ["smirk", "confident"] },
    { char: "😒", nameAr: "غير معجب", nameEn: "Unamused", tags: ["bored", "annoyed"] },
    { char: "🙄", nameAr: "عيون متدحرجة", nameEn: "Rolling Eyes", tags: ["annoyed", "whatever"] },
    { char: "😬", nameAr: "كشرة", nameEn: "Grimace", tags: ["awkward", "nervous"] },
    { char: "😮‍💨", nameAr: "تنهد", nameEn: "Exhaling", tags: ["sigh", "relief", "tired"] },
    { char: "🤥", nameAr: "كاذب", nameEn: "Lying", tags: ["lie", "pinocchio"] },
    { char: "😌", nameAr: "مرتاح", nameEn: "Relieved", tags: ["calm", "peaceful"] },
    { char: "😔", nameAr: "حزين", nameEn: "Pensive", tags: ["sad", "thoughtful"] },
    { char: "😪", nameAr: "نعسان", nameEn: "Sleepy", tags: ["sleepy", "tired"] },
    { char: "🤤", nameAr: "لعاب", nameEn: "Drooling", tags: ["drool", "hungry"] },
    { char: "😴", nameAr: "نائم", nameEn: "Sleeping", tags: ["sleep", "zzz"] },
    { char: "😷", nameAr: "كمامة", nameEn: "Medical Mask", tags: ["sick", "mask", "health"] },
    { char: "🤒", nameAr: "مريض بحرارة", nameEn: "Thermometer", tags: ["sick", "fever"] },
    { char: "🤕", nameAr: "مصاب", nameEn: "Bandage Head", tags: ["hurt", "injury"] },
    { char: "🤢", nameAr: "غثيان", nameEn: "Nauseated", tags: ["sick", "nausea"] },
    { char: "🤮", nameAr: "يتقيأ", nameEn: "Vomiting", tags: ["sick"] },
    { char: "🥵", nameAr: "حار", nameEn: "Hot Face", tags: ["hot", "heat"] },
    { char: "🥶", nameAr: "بارد", nameEn: "Cold Face", tags: ["cold", "freeze"] },
    { char: "🥴", nameAr: "مترنح", nameEn: "Woozy", tags: ["dizzy", "drunk"] },
    { char: "😵", nameAr: "مصدوم", nameEn: "Dizzy Face", tags: ["dizzy", "shock"] },
    { char: "🤯", nameAr: "رأس منفجر", nameEn: "Mind Blown", tags: ["shocked", "wow", "explode"] },
    { char: "🤠", nameAr: "كاوبوي", nameEn: "Cowboy", tags: ["hat", "western"] },
    { char: "🥳", nameAr: "احتفال", nameEn: "Partying", tags: ["party", "celebrate", "birthday"] },
    { char: "🥸", nameAr: "متنكر", nameEn: "Disguised", tags: ["disguise", "glasses", "mustache"] },
    { char: "😎", nameAr: "نظارة شمسية", nameEn: "Sunglasses", tags: ["cool", "sun"] },
    { char: "🤓", nameAr: "نظارة ذكي", nameEn: "Nerd", tags: ["nerd", "smart", "glasses"] },
    { char: "🧐", nameAr: "محقق", nameEn: "Monocle", tags: ["inspect", "detective"] },
    { char: "😕", nameAr: "محتار", nameEn: "Confused", tags: ["confused", "uncertain"] },
    { char: "🫤", nameAr: "فم مائل", nameEn: "Diagonal Mouth", tags: ["skeptical"] },
    { char: "😟", nameAr: "قلق", nameEn: "Worried", tags: ["worried", "concerned"] },
    { char: "🙁", nameAr: "حزين قليلا", nameEn: "Slightly Frowning", tags: ["sad"] },
    { char: "☹️", nameAr: "حزين", nameEn: "Frowning", tags: ["sad", "unhappy"] },
    { char: "😮", nameAr: "فم مفتوح", nameEn: "Open Mouth", tags: ["surprised", "oh"] },
    { char: "😯", nameAr: "مندهش", nameEn: "Hushed", tags: ["surprised", "quiet"] },
    { char: "😲", nameAr: "مصدوم", nameEn: "Astonished", tags: ["shocked", "surprise"] },
    { char: "😳", nameAr: "محرج", nameEn: "Flushed", tags: ["embarrassed", "red"] },
    { char: "🥺", nameAr: "عيون متوسلة", nameEn: "Pleading Eyes", tags: ["please", "cute", "beg"] },
    { char: "🥹", nameAr: "يحبس دموع", nameEn: "Holding Tears", tags: ["emotional", "touched"] },
    { char: "😦", nameAr: "فم مفتوح حزين", nameEn: "Frowning Open", tags: ["sad", "surprised"] },
    { char: "😧", nameAr: "قلق", nameEn: "Anguished", tags: ["anxious", "worried"] },
    { char: "😨", nameAr: "خائف", nameEn: "Fearful", tags: ["scared", "fear"] },
    { char: "😰", nameAr: "قلق بارد", nameEn: "Anxious Sweat", tags: ["anxious", "nervous"] },
    { char: "😥", nameAr: "حزين مرتاح", nameEn: "Sad Relieved", tags: ["sad", "relief"] },
    { char: "😢", nameAr: "يبكي", nameEn: "Crying", tags: ["cry", "sad", "tear"] },
    { char: "😭", nameAr: "يبكي بشدة", nameEn: "Loudly Crying", tags: ["cry", "sad", "loud"] },
    { char: "😱", nameAr: "صراخ", nameEn: "Screaming", tags: ["scared", "scream", "horror"] },
    { char: "😖", nameAr: "منزعج", nameEn: "Confounded", tags: ["frustrated", "upset"] },
    { char: "😣", nameAr: "مثابر", nameEn: "Persevering", tags: ["trying", "effort"] },
    { char: "😞", nameAr: "محبط", nameEn: "Disappointed", tags: ["sad", "disappointed"] },
    { char: "😓", nameAr: "عرق بارد", nameEn: "Downcast Sweat", tags: ["tired", "effort"] },
    { char: "😩", nameAr: "متعب", nameEn: "Weary", tags: ["tired", "exhausted"] },
    { char: "😫", nameAr: "مرهق", nameEn: "Tired", tags: ["tired", "exhausted"] },
    { char: "🥱", nameAr: "تثاؤب", nameEn: "Yawning", tags: ["yawn", "sleepy", "bored"] },
    { char: "😤", nameAr: "غاضب", nameEn: "Huffing", tags: ["angry", "steam", "frustrated"] },
    { char: "😡", nameAr: "غاضب جدا", nameEn: "Pouting", tags: ["angry", "mad", "red"] },
    { char: "😠", nameAr: "غضبان", nameEn: "Angry", tags: ["angry", "mad"] },
    { char: "🤬", nameAr: "يشتم", nameEn: "Cursing", tags: ["angry", "swear"] },
    { char: "😈", nameAr: "شيطان مبتسم", nameEn: "Smiling Devil", tags: ["devil", "mischief"] },
    { char: "👿", nameAr: "شيطان غاضب", nameEn: "Angry Devil", tags: ["devil", "angry"] },
    { char: "💀", nameAr: "جمجمة", nameEn: "Skull", tags: ["dead", "death", "skeleton"] },
    { char: "☠️", nameAr: "جمجمة وعظام", nameEn: "Skull Crossbones", tags: ["danger", "pirate"] },
    { char: "👻", nameAr: "شبح", nameEn: "Ghost", tags: ["ghost", "halloween", "spooky"] },
    { char: "👽", nameAr: "فضائي", nameEn: "Alien", tags: ["alien", "space", "ufo"] },
    { char: "🤖", nameAr: "روبوت", nameEn: "Robot", tags: ["robot", "technology", "ai"] },
    { char: "🎃", nameAr: "يقطينة", nameEn: "Jack-O-Lantern", tags: ["halloween", "pumpkin"] },
    { char: "😺", nameAr: "قطة سعيدة", nameEn: "Cat Grinning", tags: ["cat", "happy"] },
    { char: "😸", nameAr: "قطة مبتسمة", nameEn: "Cat Smile", tags: ["cat", "happy"] },
    { char: "😹", nameAr: "قطة ضاحكة", nameEn: "Cat Joy", tags: ["cat", "laugh"] },
    { char: "😻", nameAr: "قطة عيون قلب", nameEn: "Cat Heart Eyes", tags: ["cat", "love"] },
    { char: "😼", nameAr: "قطة ماكرة", nameEn: "Cat Smirk", tags: ["cat", "smirk"] },
    { char: "😽", nameAr: "قطة تقبل", nameEn: "Cat Kiss", tags: ["cat", "kiss"] },
    { char: "🙀", nameAr: "قطة خائفة", nameEn: "Cat Weary", tags: ["cat", "scared"] },
    { char: "😿", nameAr: "قطة حزينة", nameEn: "Cat Crying", tags: ["cat", "sad"] },
    { char: "😾", nameAr: "قطة غاضبة", nameEn: "Cat Pouting", tags: ["cat", "angry"] },
    // Hand gestures
    { char: "👋", nameAr: "تلويح", nameEn: "Wave", tags: ["hand", "hello", "bye"] },
    { char: "🤚", nameAr: "كف مرفوع", nameEn: "Raised Hand", tags: ["hand", "stop"] },
    { char: "✋", nameAr: "يد مرفوعة", nameEn: "Hand", tags: ["hand", "high five", "stop"] },
    { char: "🖐️", nameAr: "خمسة أصابع", nameEn: "Hand Spread", tags: ["hand", "five", "fingers"] },
    { char: "👌", nameAr: "أوكي", nameEn: "OK Hand", tags: ["ok", "perfect", "hand"] },
    { char: "🤌", nameAr: "إيطالي", nameEn: "Pinched Fingers", tags: ["hand", "italian"] },
    { char: "✌️", nameAr: "سلام", nameEn: "Peace", tags: ["peace", "victory", "hand"] },
    { char: "🤞", nameAr: "حظ", nameEn: "Crossed Fingers", tags: ["luck", "hope", "hand"] },
    { char: "🫰", nameAr: "قلب يد", nameEn: "Hand Heart", tags: ["love", "hand"] },
    { char: "🤟", nameAr: "حب يد", nameEn: "Love You", tags: ["love", "hand", "rock"] },
    { char: "🤘", nameAr: "روك", nameEn: "Horns", tags: ["rock", "metal", "hand"] },
    { char: "👍", nameAr: "إعجاب", nameEn: "Thumbs Up", tags: ["like", "good", "approve"] },
    { char: "👎", nameAr: "عدم إعجاب", nameEn: "Thumbs Down", tags: ["dislike", "bad"] },
    { char: "✊", nameAr: "قبضة مرفوعة", nameEn: "Raised Fist", tags: ["power", "fight"] },
    { char: "👊", nameAr: "لكمة", nameEn: "Fist Bump", tags: ["punch", "power"] },
    { char: "👏", nameAr: "تصفيق", nameEn: "Clapping", tags: ["clap", "bravo", "applause"] },
    { char: "🙌", nameAr: "يدين مرفوعة", nameEn: "Raising Hands", tags: ["celebration", "praise"] },
    { char: "🫶", nameAr: "قلب يدين", nameEn: "Heart Hands", tags: ["love", "heart"] },
    { char: "👐", nameAr: "يدين مفتوحة", nameEn: "Open Hands", tags: ["hand", "open"] },
    { char: "🤲", nameAr: "دعاء", nameEn: "Palms Up", tags: ["pray", "hands"] },
    { char: "🙏", nameAr: "رجاء/دعاء", nameEn: "Folded Hands", tags: ["pray", "please", "thank"] },
    { char: "💪", nameAr: "عضلة", nameEn: "Flexed Bicep", tags: ["strong", "muscle", "power"] },
    // Hearts
    { char: "❤️", nameAr: "قلب أحمر", nameEn: "Red Heart", tags: ["love", "heart", "red"] },
    { char: "🧡", nameAr: "قلب برتقالي", nameEn: "Orange Heart", tags: ["love", "heart", "orange"] },
    { char: "💛", nameAr: "قلب أصفر", nameEn: "Yellow Heart", tags: ["love", "heart", "yellow"] },
    { char: "💚", nameAr: "قلب أخضر", nameEn: "Green Heart", tags: ["love", "heart", "green"] },
    { char: "💙", nameAr: "قلب أزرق", nameEn: "Blue Heart", tags: ["love", "heart", "blue"] },
    { char: "💜", nameAr: "قلب بنفسجي", nameEn: "Purple Heart", tags: ["love", "heart", "purple"] },
    { char: "🖤", nameAr: "قلب أسود", nameEn: "Black Heart", tags: ["love", "heart", "black"] },
    { char: "🤍", nameAr: "قلب أبيض", nameEn: "White Heart", tags: ["love", "heart", "white"] },
    { char: "🩷", nameAr: "قلب وردي", nameEn: "Pink Heart", tags: ["love", "heart", "pink"] },
    { char: "💖", nameAr: "قلب لامع", nameEn: "Sparkling Heart", tags: ["love", "sparkle"] },
    { char: "💝", nameAr: "قلب شريط", nameEn: "Heart Ribbon", tags: ["love", "gift"] },
    { char: "💘", nameAr: "قلب سهم", nameEn: "Heart Arrow", tags: ["love", "cupid"] },
    { char: "💗", nameAr: "قلب ينمو", nameEn: "Growing Heart", tags: ["love"] },
    { char: "💓", nameAr: "قلب ينبض", nameEn: "Beating Heart", tags: ["love", "pulse"] },
    { char: "💕", nameAr: "قلبين", nameEn: "Two Hearts", tags: ["love"] },
    { char: "💞", nameAr: "قلوب دائرية", nameEn: "Revolving Hearts", tags: ["love"] },
  ];

  const animals: SymDef[] = [
    { char: "🐶", nameAr: "كلب", nameEn: "Dog Face", tags: ["dog", "pet", "puppy"] },
    { char: "🐱", nameAr: "قطة", nameEn: "Cat Face", tags: ["cat", "pet", "kitten"] },
    { char: "🐭", nameAr: "فأر", nameEn: "Mouse", tags: ["mouse", "rat"] },
    { char: "🐹", nameAr: "هامستر", nameEn: "Hamster", tags: ["hamster", "pet"] },
    { char: "🐰", nameAr: "أرنب", nameEn: "Rabbit", tags: ["rabbit", "bunny"] },
    { char: "🦊", nameAr: "ثعلب", nameEn: "Fox", tags: ["fox", "clever"] },
    { char: "🐻", nameAr: "دب", nameEn: "Bear", tags: ["bear", "teddy"] },
    { char: "🐼", nameAr: "باندا", nameEn: "Panda", tags: ["panda", "bear"] },
    { char: "🐻‍❄️", nameAr: "دب قطبي", nameEn: "Polar Bear", tags: ["bear", "arctic", "ice"] },
    { char: "🐨", nameAr: "كوالا", nameEn: "Koala", tags: ["koala", "australia"] },
    { char: "🐯", nameAr: "نمر", nameEn: "Tiger", tags: ["tiger", "wild", "cat"] },
    { char: "🦁", nameAr: "أسد", nameEn: "Lion", tags: ["lion", "king", "wild"] },
    { char: "🐮", nameAr: "بقرة", nameEn: "Cow", tags: ["cow", "farm", "milk"] },
    { char: "🐷", nameAr: "خنزير", nameEn: "Pig", tags: ["pig", "farm"] },
    { char: "🐸", nameAr: "ضفدع", nameEn: "Frog", tags: ["frog", "green"] },
    { char: "🐵", nameAr: "قرد", nameEn: "Monkey", tags: ["monkey", "banana"] },
    { char: "🙈", nameAr: "قرد لا يرى", nameEn: "See No Evil", tags: ["monkey", "hide"] },
    { char: "🙉", nameAr: "قرد لا يسمع", nameEn: "Hear No Evil", tags: ["monkey", "deaf"] },
    { char: "🙊", nameAr: "قرد لا يتكلم", nameEn: "Speak No Evil", tags: ["monkey", "silent"] },
    { char: "🐔", nameAr: "دجاجة", nameEn: "Chicken", tags: ["chicken", "farm", "bird"] },
    { char: "🐧", nameAr: "بطريق", nameEn: "Penguin", tags: ["penguin", "ice", "bird"] },
    { char: "🐦", nameAr: "طائر", nameEn: "Bird", tags: ["bird", "fly"] },
    { char: "🐤", nameAr: "كتكوت", nameEn: "Chick", tags: ["chick", "baby", "bird"] },
    { char: "🐣", nameAr: "كتكوت يفقس", nameEn: "Hatching Chick", tags: ["chick", "egg", "birth"] },
    { char: "🦆", nameAr: "بطة", nameEn: "Duck", tags: ["duck", "bird", "water"] },
    { char: "🦅", nameAr: "نسر", nameEn: "Eagle", tags: ["eagle", "bird", "powerful"] },
    { char: "🦉", nameAr: "بومة", nameEn: "Owl", tags: ["owl", "night", "wise"] },
    { char: "🦇", nameAr: "خفاش", nameEn: "Bat", tags: ["bat", "night", "vampire"] },
    { char: "🐺", nameAr: "ذئب", nameEn: "Wolf", tags: ["wolf", "wild"] },
    { char: "🐗", nameAr: "خنزير بري", nameEn: "Boar", tags: ["boar", "wild"] },
    { char: "🐴", nameAr: "حصان", nameEn: "Horse", tags: ["horse", "ride"] },
    { char: "🦄", nameAr: "يونيكورن", nameEn: "Unicorn", tags: ["unicorn", "magic", "fantasy"] },
    { char: "🐝", nameAr: "نحلة", nameEn: "Bee", tags: ["bee", "honey", "insect"] },
    { char: "🪱", nameAr: "دودة", nameEn: "Worm", tags: ["worm", "insect"] },
    { char: "🐛", nameAr: "حشرة", nameEn: "Bug", tags: ["bug", "caterpillar", "insect"] },
    { char: "🦋", nameAr: "فراشة", nameEn: "Butterfly", tags: ["butterfly", "insect", "beautiful"] },
    { char: "🐌", nameAr: "حلزون", nameEn: "Snail", tags: ["snail", "slow"] },
    { char: "🐞", nameAr: "دعسوقة", nameEn: "Ladybug", tags: ["ladybug", "insect", "red"] },
    { char: "🐜", nameAr: "نملة", nameEn: "Ant", tags: ["ant", "insect", "work"] },
    { char: "🪰", nameAr: "ذبابة", nameEn: "Fly", tags: ["fly", "insect"] },
    { char: "🦗", nameAr: "جندب", nameEn: "Cricket", tags: ["cricket", "insect"] },
    { char: "🕷️", nameAr: "عنكبوت", nameEn: "Spider", tags: ["spider", "web", "insect"] },
    { char: "🦂", nameAr: "عقرب", nameEn: "Scorpion", tags: ["scorpion", "desert"] },
    { char: "🐢", nameAr: "سلحفاة", nameEn: "Turtle", tags: ["turtle", "slow", "shell"] },
    { char: "🐍", nameAr: "ثعبان", nameEn: "Snake", tags: ["snake", "reptile"] },
    { char: "🦎", nameAr: "سحلية", nameEn: "Lizard", tags: ["lizard", "reptile"] },
    { char: "🐊", nameAr: "تمساح", nameEn: "Crocodile", tags: ["crocodile", "alligator"] },
    { char: "🦈", nameAr: "قرش", nameEn: "Shark", tags: ["shark", "fish", "ocean", "danger"] },
    { char: "🐳", nameAr: "حوت", nameEn: "Whale", tags: ["whale", "ocean", "big"] },
    { char: "🐋", nameAr: "حوت كبير", nameEn: "Whale2", tags: ["whale", "ocean"] },
    { char: "🐬", nameAr: "دولفين", nameEn: "Dolphin", tags: ["dolphin", "ocean", "smart"] },
    { char: "🐟", nameAr: "سمكة", nameEn: "Fish", tags: ["fish", "ocean", "water"] },
    { char: "🐠", nameAr: "سمكة استوائية", nameEn: "Tropical Fish", tags: ["fish", "colorful"] },
    { char: "🐡", nameAr: "سمكة منتفخة", nameEn: "Blowfish", tags: ["fish", "puffer"] },
    { char: "🦐", nameAr: "جمبري", nameEn: "Shrimp", tags: ["shrimp", "seafood"] },
    { char: "🦀", nameAr: "سلطعون", nameEn: "Crab", tags: ["crab", "seafood"] },
    { char: "🐙", nameAr: "أخطبوط", nameEn: "Octopus", tags: ["octopus", "ocean"] },
    { char: "🪸", nameAr: "مرجان", nameEn: "Coral", tags: ["coral", "ocean", "reef"] },
    { char: "🦩", nameAr: "فلامنغو", nameEn: "Flamingo", tags: ["flamingo", "pink", "bird"] },
    { char: "🦚", nameAr: "طاووس", nameEn: "Peacock", tags: ["peacock", "beautiful", "bird"] },
    { char: "🦜", nameAr: "ببغاء", nameEn: "Parrot", tags: ["parrot", "bird", "colorful"] },
    { char: "🦢", nameAr: "بجعة", nameEn: "Swan", tags: ["swan", "bird", "elegant"] },
    { char: "🦃", nameAr: "ديك رومي", nameEn: "Turkey", tags: ["turkey", "bird"] },
    { char: "🐓", nameAr: "ديك", nameEn: "Rooster", tags: ["rooster", "bird", "farm"] },
    { char: "🐕", nameAr: "كلب", nameEn: "Dog", tags: ["dog", "pet"] },
    { char: "🐈", nameAr: "قط", nameEn: "Cat", tags: ["cat", "pet"] },
    { char: "🐎", nameAr: "فرس", nameEn: "Racing Horse", tags: ["horse", "race", "fast"] },
    { char: "🐄", nameAr: "بقرة", nameEn: "Cow2", tags: ["cow", "farm"] },
    { char: "🐑", nameAr: "خروف", nameEn: "Sheep", tags: ["sheep", "wool", "farm"] },
    { char: "🐐", nameAr: "ماعز", nameEn: "Goat", tags: ["goat", "farm"] },
    { char: "🦌", nameAr: "غزال", nameEn: "Deer", tags: ["deer", "forest"] },
    { char: "🐘", nameAr: "فيل", nameEn: "Elephant", tags: ["elephant", "big", "africa"] },
    { char: "🦏", nameAr: "وحيد القرن", nameEn: "Rhinoceros", tags: ["rhino", "africa"] },
    { char: "🦛", nameAr: "فرس النهر", nameEn: "Hippopotamus", tags: ["hippo", "africa", "water"] },
    { char: "🐪", nameAr: "جمل", nameEn: "Camel", tags: ["camel", "desert", "arab"] },
    { char: "🐫", nameAr: "جمل سنامين", nameEn: "Two Hump Camel", tags: ["camel", "desert"] },
    { char: "🦒", nameAr: "زرافة", nameEn: "Giraffe", tags: ["giraffe", "tall", "africa"] },
    { char: "🦘", nameAr: "كنغر", nameEn: "Kangaroo", tags: ["kangaroo", "australia", "jump"] },
    { char: "🦍", nameAr: "غوريلا", nameEn: "Gorilla", tags: ["gorilla", "strong"] },
    { char: "🦧", nameAr: "أورانغوتان", nameEn: "Orangutan", tags: ["orangutan", "monkey"] },
    { char: "🐾", nameAr: "بصمة حيوان", nameEn: "Paw Prints", tags: ["paw", "animal", "pet"] },
    { char: "🦔", nameAr: "قنفذ", nameEn: "Hedgehog", tags: ["hedgehog", "cute"] },
    { char: "🦦", nameAr: "قضاعة", nameEn: "Otter", tags: ["otter", "water", "cute"] },
    { char: "🦥", nameAr: "كسلان", nameEn: "Sloth", tags: ["sloth", "lazy", "slow"] },
    { char: "🐿️", nameAr: "سنجاب", nameEn: "Squirrel", tags: ["squirrel", "nuts"] },
    { char: "🦫", nameAr: "قندس", nameEn: "Beaver", tags: ["beaver", "build"] },
  ];

  const natureElements: SymDef[] = [
    { char: "☀️", nameAr: "شمس", nameEn: "Sun", tags: ["sun", "bright", "hot", "day"] },
    { char: "🌤️", nameAr: "شمس سحاب", nameEn: "Sun Cloud", tags: ["sun", "cloud", "weather"] },
    { char: "⛅", nameAr: "غيوم وشمس", nameEn: "Partly Cloudy", tags: ["cloud", "sun", "weather"] },
    { char: "🌥️", nameAr: "شمس خلف سحابة", nameEn: "Sun Behind Cloud", tags: ["cloud", "weather"] },
    { char: "☁️", nameAr: "سحابة", nameEn: "Cloud", tags: ["cloud", "weather"] },
    { char: "🌦️", nameAr: "مطر وشمس", nameEn: "Sun Rain", tags: ["rain", "sun", "weather"] },
    { char: "🌧️", nameAr: "مطر", nameEn: "Rain Cloud", tags: ["rain", "weather", "water"] },
    { char: "⛈️", nameAr: "عاصفة رعدية", nameEn: "Thunder Storm", tags: ["storm", "lightning", "weather"] },
    { char: "🌩️", nameAr: "برق", nameEn: "Lightning", tags: ["lightning", "storm"] },
    { char: "🌨️", nameAr: "ثلج", nameEn: "Snow Cloud", tags: ["snow", "winter", "cold"] },
    { char: "❄️", nameAr: "رقاقة ثلج", nameEn: "Snowflake", tags: ["snow", "ice", "winter", "cold"] },
    { char: "⛄", nameAr: "رجل ثلج", nameEn: "Snowman", tags: ["snow", "winter", "cold"] },
    { char: "🌪️", nameAr: "إعصار", nameEn: "Tornado", tags: ["tornado", "storm", "wind"] },
    { char: "🌫️", nameAr: "ضباب", nameEn: "Fog", tags: ["fog", "mist", "weather"] },
    { char: "🌊", nameAr: "موجة", nameEn: "Wave", tags: ["wave", "ocean", "water", "sea"] },
    { char: "💧", nameAr: "قطرة ماء", nameEn: "Droplet", tags: ["water", "drop", "rain"] },
    { char: "💦", nameAr: "رذاذ", nameEn: "Sweat Drops", tags: ["water", "splash"] },
    { char: "🌈", nameAr: "قوس قزح", nameEn: "Rainbow", tags: ["rainbow", "colors", "beautiful"] },
    { char: "🌙", nameAr: "هلال", nameEn: "Crescent Moon", tags: ["moon", "night", "islam"] },
    { char: "🌕", nameAr: "بدر", nameEn: "Full Moon", tags: ["moon", "full", "night"] },
    { char: "🌖", nameAr: "قمر متضائل", nameEn: "Waning Moon", tags: ["moon", "phase"] },
    { char: "🌗", nameAr: "نصف قمر أخير", nameEn: "Last Quarter", tags: ["moon", "half"] },
    { char: "🌘", nameAr: "هلال متضائل", nameEn: "Waning Crescent", tags: ["moon", "phase"] },
    { char: "🌑", nameAr: "قمر جديد", nameEn: "New Moon", tags: ["moon", "dark", "night"] },
    { char: "🌒", nameAr: "هلال متصاعد", nameEn: "Waxing Crescent", tags: ["moon", "phase"] },
    { char: "🌓", nameAr: "نصف قمر أول", nameEn: "First Quarter", tags: ["moon", "half"] },
    { char: "🌔", nameAr: "قمر متصاعد", nameEn: "Waxing Gibbous", tags: ["moon", "phase"] },
    { char: "⭐", nameAr: "نجمة", nameEn: "Star", tags: ["star", "shine", "gold"] },
    { char: "🌟", nameAr: "نجمة متوهجة", nameEn: "Glowing Star", tags: ["star", "glow", "bright"] },
    { char: "✨", nameAr: "بريق", nameEn: "Sparkles", tags: ["sparkle", "shine", "magic"] },
    { char: "💫", nameAr: "نجمة دوارة", nameEn: "Dizzy Star", tags: ["star", "dizzy"] },
    { char: "🔥", nameAr: "نار", nameEn: "Fire", tags: ["fire", "hot", "flame"] },
    { char: "🌋", nameAr: "بركان", nameEn: "Volcano", tags: ["volcano", "lava", "eruption"] },
    { char: "🌍", nameAr: "الأرض أفريقيا", nameEn: "Earth Africa", tags: ["earth", "globe", "world"] },
    { char: "🌎", nameAr: "الأرض أمريكا", nameEn: "Earth Americas", tags: ["earth", "globe"] },
    { char: "🌏", nameAr: "الأرض آسيا", nameEn: "Earth Asia", tags: ["earth", "globe"] },
    { char: "🪐", nameAr: "كوكب", nameEn: "Planet", tags: ["planet", "saturn", "ring", "space"] },
    // Plants
    { char: "🌱", nameAr: "شتلة", nameEn: "Seedling", tags: ["plant", "grow", "seed", "green"] },
    { char: "🪴", nameAr: "نبتة", nameEn: "Potted Plant", tags: ["plant", "pot", "green"] },
    { char: "🌲", nameAr: "شجرة صنوبر", nameEn: "Evergreen", tags: ["tree", "pine", "forest"] },
    { char: "🌳", nameAr: "شجرة", nameEn: "Deciduous Tree", tags: ["tree", "green", "forest"] },
    { char: "🌴", nameAr: "نخلة", nameEn: "Palm Tree", tags: ["palm", "tropical", "beach"] },
    { char: "🌵", nameAr: "صبار", nameEn: "Cactus", tags: ["cactus", "desert", "plant"] },
    { char: "🎋", nameAr: "خيزران", nameEn: "Bamboo", tags: ["bamboo", "plant", "green"] },
    { char: "🎍", nameAr: "أبواب صنوبر", nameEn: "Pine Decoration", tags: ["pine", "decoration"] },
    { char: "🍀", nameAr: "برسيم رباعي", nameEn: "Four Leaf Clover", tags: ["clover", "luck", "green"] },
    { char: "☘️", nameAr: "برسيم", nameEn: "Shamrock", tags: ["clover", "irish", "green"] },
    { char: "🍃", nameAr: "ورقة شجر", nameEn: "Leaf Fluttering", tags: ["leaf", "green", "wind"] },
    { char: "🍂", nameAr: "أوراق خريف", nameEn: "Fallen Leaf", tags: ["leaf", "autumn", "fall"] },
    { char: "🍁", nameAr: "ورقة قيقب", nameEn: "Maple Leaf", tags: ["maple", "leaf", "canada"] },
    { char: "🌾", nameAr: "قمح", nameEn: "Rice Ear", tags: ["wheat", "rice", "grain", "farm"] },
    { char: "🌿", nameAr: "عشب", nameEn: "Herb", tags: ["herb", "green", "plant"] },
    // Flowers
    { char: "🌸", nameAr: "زهرة كرز", nameEn: "Cherry Blossom", tags: ["flower", "cherry", "pink", "spring"] },
    { char: "💮", nameAr: "زهرة بيضاء", nameEn: "White Flower", tags: ["flower", "white"] },
    { char: "🏵️", nameAr: "وردة", nameEn: "Rosette", tags: ["flower", "rose"] },
    { char: "🌹", nameAr: "وردة حمراء", nameEn: "Rose", tags: ["rose", "flower", "red", "love"] },
    { char: "🥀", nameAr: "وردة ذابلة", nameEn: "Wilted Rose", tags: ["flower", "sad", "dead"] },
    { char: "🌺", nameAr: "كركديه", nameEn: "Hibiscus", tags: ["flower", "tropical", "red"] },
    { char: "🌻", nameAr: "دوار الشمس", nameEn: "Sunflower", tags: ["flower", "sun", "yellow"] },
    { char: "🌼", nameAr: "زهرة", nameEn: "Blossom", tags: ["flower", "bloom"] },
    { char: "🌷", nameAr: "توليب", nameEn: "Tulip", tags: ["flower", "tulip", "spring"] },
    { char: "🪻", nameAr: "لافندر", nameEn: "Lavender", tags: ["flower", "purple", "fragrant"] },
    // Fruits
    { char: "🍎", nameAr: "تفاحة حمراء", nameEn: "Red Apple", tags: ["apple", "fruit", "red"] },
    { char: "🍏", nameAr: "تفاحة خضراء", nameEn: "Green Apple", tags: ["apple", "fruit", "green"] },
    { char: "🍐", nameAr: "كمثرى", nameEn: "Pear", tags: ["pear", "fruit"] },
    { char: "🍊", nameAr: "برتقالة", nameEn: "Orange", tags: ["orange", "fruit", "citrus"] },
    { char: "🍋", nameAr: "ليمون", nameEn: "Lemon", tags: ["lemon", "fruit", "citrus", "yellow"] },
    { char: "🍌", nameAr: "موزة", nameEn: "Banana", tags: ["banana", "fruit", "yellow"] },
    { char: "🍉", nameAr: "بطيخ", nameEn: "Watermelon", tags: ["watermelon", "fruit", "summer"] },
    { char: "🍇", nameAr: "عنب", nameEn: "Grapes", tags: ["grapes", "fruit", "purple"] },
    { char: "🍓", nameAr: "فراولة", nameEn: "Strawberry", tags: ["strawberry", "fruit", "red"] },
    { char: "🫐", nameAr: "توت أزرق", nameEn: "Blueberries", tags: ["blueberry", "fruit"] },
    { char: "🍒", nameAr: "كرز", nameEn: "Cherries", tags: ["cherry", "fruit", "red"] },
    { char: "🍑", nameAr: "خوخ", nameEn: "Peach", tags: ["peach", "fruit"] },
    { char: "🥭", nameAr: "مانجو", nameEn: "Mango", tags: ["mango", "fruit", "tropical"] },
    { char: "🍍", nameAr: "أناناس", nameEn: "Pineapple", tags: ["pineapple", "fruit", "tropical"] },
    { char: "🥥", nameAr: "جوز هند", nameEn: "Coconut", tags: ["coconut", "tropical"] },
    { char: "🥝", nameAr: "كيوي", nameEn: "Kiwi", tags: ["kiwi", "fruit", "green"] },
    { char: "🌰", nameAr: "كستناء", nameEn: "Chestnut", tags: ["chestnut", "nut", "autumn"] },
    { char: "🥜", nameAr: "فول سوداني", nameEn: "Peanuts", tags: ["peanut", "nut"] },
  ];

  const shapesColors: SymDef[] = [
    { char: "🔴", nameAr: "دائرة حمراء", nameEn: "Red Circle", tags: ["circle", "red", "shape"] },
    { char: "🟠", nameAr: "دائرة برتقالية", nameEn: "Orange Circle", tags: ["circle", "orange", "shape"] },
    { char: "🟡", nameAr: "دائرة صفراء", nameEn: "Yellow Circle", tags: ["circle", "yellow", "shape"] },
    { char: "🟢", nameAr: "دائرة خضراء", nameEn: "Green Circle", tags: ["circle", "green", "shape"] },
    { char: "🔵", nameAr: "دائرة زرقاء", nameEn: "Blue Circle", tags: ["circle", "blue", "shape"] },
    { char: "🟣", nameAr: "دائرة بنفسجية", nameEn: "Purple Circle", tags: ["circle", "purple", "shape"] },
    { char: "🟤", nameAr: "دائرة بنية", nameEn: "Brown Circle", tags: ["circle", "brown", "shape"] },
    { char: "⚫", nameAr: "دائرة سوداء", nameEn: "Black Circle", tags: ["circle", "black", "shape"] },
    { char: "⚪", nameAr: "دائرة بيضاء", nameEn: "White Circle", tags: ["circle", "white", "shape"] },
    { char: "🔺", nameAr: "مثلث أحمر", nameEn: "Red Triangle Up", tags: ["triangle", "red", "shape", "up"] },
    { char: "🔻", nameAr: "مثلث أحمر لأسفل", nameEn: "Red Triangle Down", tags: ["triangle", "red", "shape", "down"] },
    { char: "🔶", nameAr: "معين برتقالي كبير", nameEn: "Large Orange Diamond", tags: ["diamond", "orange", "shape"] },
    { char: "🔷", nameAr: "معين أزرق كبير", nameEn: "Large Blue Diamond", tags: ["diamond", "blue", "shape"] },
    { char: "🔸", nameAr: "معين برتقالي صغير", nameEn: "Small Orange Diamond", tags: ["diamond", "orange", "shape"] },
    { char: "🔹", nameAr: "معين أزرق صغير", nameEn: "Small Blue Diamond", tags: ["diamond", "blue", "shape"] },
    { char: "🟥", nameAr: "مربع أحمر", nameEn: "Red Square", tags: ["square", "red", "shape"] },
    { char: "🟧", nameAr: "مربع برتقالي", nameEn: "Orange Square", tags: ["square", "orange", "shape"] },
    { char: "🟨", nameAr: "مربع أصفر", nameEn: "Yellow Square", tags: ["square", "yellow", "shape"] },
    { char: "🟩", nameAr: "مربع أخضر", nameEn: "Green Square", tags: ["square", "green", "shape"] },
    { char: "🟦", nameAr: "مربع أزرق", nameEn: "Blue Square", tags: ["square", "blue", "shape"] },
    { char: "🟪", nameAr: "مربع بنفسجي", nameEn: "Purple Square", tags: ["square", "purple", "shape"] },
    { char: "🟫", nameAr: "مربع بني", nameEn: "Brown Square", tags: ["square", "brown", "shape"] },
    { char: "⬛", nameAr: "مربع أسود كبير", nameEn: "Black Large Square", tags: ["square", "black", "shape"] },
    { char: "⬜", nameAr: "مربع أبيض كبير", nameEn: "White Large Square", tags: ["square", "white", "shape"] },
    { char: "◾", nameAr: "مربع أسود متوسط", nameEn: "Black Medium Square", tags: ["square", "black"] },
    { char: "◽", nameAr: "مربع أبيض متوسط", nameEn: "White Medium Square", tags: ["square", "white"] },
    { char: "▪️", nameAr: "مربع أسود صغير", nameEn: "Black Small Square", tags: ["square", "black", "small"] },
    { char: "▫️", nameAr: "مربع أبيض صغير", nameEn: "White Small Square", tags: ["square", "white", "small"] },
    { char: "🔲", nameAr: "زر أسود مربع", nameEn: "Black Square Button", tags: ["button", "square", "black"] },
    { char: "🔳", nameAr: "زر أبيض مربع", nameEn: "White Square Button", tags: ["button", "square", "white"] },
    { char: "⭕", nameAr: "دائرة حمراء فارغة", nameEn: "Hollow Red Circle", tags: ["circle", "red", "hollow"] },
    { char: "💠", nameAr: "معين بنقطة", nameEn: "Diamond Dot", tags: ["diamond", "shape", "cute"] },
    { char: "♦️", nameAr: "ماسة", nameEn: "Diamond Suit", tags: ["diamond", "card", "shape"] },
    { char: "♠️", nameAr: "بستوني", nameEn: "Spade Suit", tags: ["spade", "card", "shape"] },
    { char: "♣️", nameAr: "سباتي", nameEn: "Club Suit", tags: ["club", "card", "shape"] },
    { char: "♥️", nameAr: "قلب", nameEn: "Heart Suit", tags: ["heart", "card", "shape", "love"] },
    { char: "✳️", nameAr: "نجمة ثمانية مفرغة", nameEn: "Eight Spoked Star", tags: ["star", "shape"] },
    { char: "✴️", nameAr: "نجمة ثمانية", nameEn: "Eight Pointed Star", tags: ["star", "shape"] },
    { char: "🔯", nameAr: "نجمة سداسية", nameEn: "Six Pointed Star", tags: ["star", "shape", "hexagram"] },
    { char: "⬆️", nameAr: "سهم أعلى", nameEn: "Up Arrow", tags: ["arrow", "up", "direction"] },
    { char: "⬇️", nameAr: "سهم أسفل", nameEn: "Down Arrow", tags: ["arrow", "down", "direction"] },
    { char: "➡️", nameAr: "سهم يمين", nameEn: "Right Arrow", tags: ["arrow", "right", "direction"] },
    { char: "⬅️", nameAr: "سهم يسار", nameEn: "Left Arrow", tags: ["arrow", "left", "direction"] },
    { char: "↗️", nameAr: "سهم أعلى يمين", nameEn: "Upper Right Arrow", tags: ["arrow", "diagonal"] },
    { char: "↘️", nameAr: "سهم أسفل يمين", nameEn: "Lower Right Arrow", tags: ["arrow", "diagonal"] },
    { char: "↙️", nameAr: "سهم أسفل يسار", nameEn: "Lower Left Arrow", tags: ["arrow", "diagonal"] },
    { char: "↖️", nameAr: "سهم أعلى يسار", nameEn: "Upper Left Arrow", tags: ["arrow", "diagonal"] },
    { char: "🔄", nameAr: "أسهم دائرية", nameEn: "Counterclockwise Arrows", tags: ["arrow", "refresh", "cycle"] },
    { char: "🔀", nameAr: "عشوائي", nameEn: "Shuffle", tags: ["shuffle", "random", "arrows"] },
    { char: "⚡", nameAr: "برق", nameEn: "Zap", tags: ["lightning", "power", "energy", "fast"] },
    { char: "💎", nameAr: "ألماس", nameEn: "Gem", tags: ["diamond", "gem", "jewel", "precious"] },
    { char: "🫧", nameAr: "فقاعات", nameEn: "Bubbles", tags: ["bubbles", "float", "soap"] },
  ];

  const educationalTools: SymDef[] = [
    { char: "📚", nameAr: "كتب", nameEn: "Books", tags: ["book", "study", "learn", "library"] },
    { char: "📖", nameAr: "كتاب مفتوح", nameEn: "Open Book", tags: ["book", "read", "study"] },
    { char: "📕", nameAr: "كتاب أحمر", nameEn: "Red Book", tags: ["book", "red"] },
    { char: "📗", nameAr: "كتاب أخضر", nameEn: "Green Book", tags: ["book", "green"] },
    { char: "📘", nameAr: "كتاب أزرق", nameEn: "Blue Book", tags: ["book", "blue"] },
    { char: "📙", nameAr: "كتاب برتقالي", nameEn: "Orange Book", tags: ["book", "orange"] },
    { char: "📓", nameAr: "دفتر", nameEn: "Notebook", tags: ["notebook", "write"] },
    { char: "📒", nameAr: "دفتر أصفر", nameEn: "Ledger", tags: ["notebook", "yellow"] },
    { char: "📃", nameAr: "ورقة مطوية", nameEn: "Page Curl", tags: ["paper", "document"] },
    { char: "📄", nameAr: "صفحة", nameEn: "Page", tags: ["paper", "document", "file"] },
    { char: "📑", nameAr: "علامات صفحات", nameEn: "Bookmark Tabs", tags: ["bookmark", "tabs"] },
    { char: "📝", nameAr: "مذكرة", nameEn: "Memo", tags: ["note", "write", "pencil"] },
    { char: "✏️", nameAr: "قلم رصاص", nameEn: "Pencil", tags: ["pencil", "write", "draw"] },
    { char: "✒️", nameAr: "قلم حبر أسود", nameEn: "Black Pen", tags: ["pen", "write", "ink"] },
    { char: "🖊️", nameAr: "قلم حبر", nameEn: "Pen", tags: ["pen", "write"] },
    { char: "🖋️", nameAr: "قلم حبر فاخر", nameEn: "Fountain Pen", tags: ["pen", "fancy", "write"] },
    { char: "🖌️", nameAr: "فرشاة رسم", nameEn: "Paintbrush", tags: ["brush", "paint", "art"] },
    { char: "🖍️", nameAr: "تلوين", nameEn: "Crayon", tags: ["crayon", "color", "draw", "art"] },
    { char: "🔍", nameAr: "عدسة مكبرة", nameEn: "Magnifying Glass", tags: ["search", "look", "zoom"] },
    { char: "🔎", nameAr: "عدسة مكبرة يمين", nameEn: "Magnifying Right", tags: ["search", "look"] },
    { char: "📐", nameAr: "مثلث هندسي", nameEn: "Triangle Ruler", tags: ["ruler", "geometry", "math"] },
    { char: "📏", nameAr: "مسطرة", nameEn: "Straight Ruler", tags: ["ruler", "measure", "math"] },
    { char: "🧮", nameAr: "معداد", nameEn: "Abacus", tags: ["abacus", "math", "count", "calculate"] },
    { char: "🗂️", nameAr: "ملفات", nameEn: "File Dividers", tags: ["file", "organize", "folder"] },
    { char: "📁", nameAr: "مجلد", nameEn: "File Folder", tags: ["folder", "organize"] },
    { char: "📂", nameAr: "مجلد مفتوح", nameEn: "Open Folder", tags: ["folder", "open"] },
    { char: "🗃️", nameAr: "صندوق بطاقات", nameEn: "Card Box", tags: ["box", "organize", "index"] },
    { char: "🗄️", nameAr: "خزانة ملفات", nameEn: "File Cabinet", tags: ["cabinet", "storage"] },
    { char: "📊", nameAr: "رسم بياني", nameEn: "Bar Chart", tags: ["chart", "graph", "data", "statistics"] },
    { char: "📈", nameAr: "رسم صاعد", nameEn: "Chart Increasing", tags: ["chart", "up", "growth", "progress"] },
    { char: "📉", nameAr: "رسم هابط", nameEn: "Chart Decreasing", tags: ["chart", "down", "decrease"] },
    { char: "🧪", nameAr: "أنبوب اختبار", nameEn: "Test Tube", tags: ["science", "chemistry", "lab", "experiment"] },
    { char: "🔬", nameAr: "مجهر", nameEn: "Microscope", tags: ["science", "biology", "lab", "research"] },
    { char: "🔭", nameAr: "تلسكوب", nameEn: "Telescope", tags: ["science", "astronomy", "space", "stars"] },
    { char: "🧬", nameAr: "حمض نووي", nameEn: "DNA", tags: ["science", "biology", "genetics", "dna"] },
    { char: "🧲", nameAr: "مغناطيس", nameEn: "Magnet", tags: ["magnet", "physics", "attract"] },
    { char: "⚗️", nameAr: "قارورة", nameEn: "Alembic", tags: ["science", "chemistry", "flask"] },
    { char: "🌡️", nameAr: "ميزان حرارة", nameEn: "Thermometer", tags: ["temperature", "heat", "science"] },
    { char: "💻", nameAr: "لابتوب", nameEn: "Laptop", tags: ["computer", "laptop", "tech", "code"] },
    { char: "🖥️", nameAr: "كمبيوتر", nameEn: "Desktop", tags: ["computer", "monitor", "screen"] },
    { char: "⌨️", nameAr: "لوحة مفاتيح", nameEn: "Keyboard", tags: ["keyboard", "type", "computer"] },
    { char: "🖱️", nameAr: "فأرة", nameEn: "Mouse", tags: ["mouse", "computer", "click"] },
    { char: "📱", nameAr: "هاتف", nameEn: "Mobile Phone", tags: ["phone", "mobile", "smartphone"] },
    { char: "🎒", nameAr: "حقيبة مدرسة", nameEn: "Backpack", tags: ["backpack", "school", "bag"] },
    { char: "🏫", nameAr: "مدرسة", nameEn: "School", tags: ["school", "building", "education"] },
    { char: "🎓", nameAr: "قبعة تخرج", nameEn: "Graduation Cap", tags: ["graduate", "success", "education"] },
    { char: "🧑‍🏫", nameAr: "معلم", nameEn: "Teacher", tags: ["teacher", "education", "school"] },
    { char: "🧑‍🎓", nameAr: "طالب", nameEn: "Student", tags: ["student", "learn", "school"] },
    { char: "🗺️", nameAr: "خريطة العالم", nameEn: "World Map", tags: ["map", "geography", "world"] },
    { char: "🧭", nameAr: "بوصلة", nameEn: "Compass", tags: ["compass", "direction", "navigation"] },
    { char: "⏰", nameAr: "ساعة منبه", nameEn: "Alarm Clock", tags: ["clock", "time", "alarm", "wake"] },
    { char: "⏱️", nameAr: "ساعة إيقاف", nameEn: "Stopwatch", tags: ["timer", "time", "speed"] },
    { char: "⌛", nameAr: "ساعة رملية", nameEn: "Hourglass", tags: ["time", "sand", "timer"] },
    { char: "⏳", nameAr: "ساعة رملية تعمل", nameEn: "Hourglass Running", tags: ["time", "wait", "timer"] },
    { char: "🔔", nameAr: "جرس", nameEn: "Bell", tags: ["bell", "ring", "notification", "school"] },
    { char: "📌", nameAr: "دبوس", nameEn: "Pushpin", tags: ["pin", "mark", "important"] },
    { char: "📎", nameAr: "مشبك ورق", nameEn: "Paperclip", tags: ["clip", "paper", "attach"] },
    { char: "📍", nameAr: "دبوس خريطة", nameEn: "Map Pin", tags: ["pin", "location", "map"] },
    { char: "🗑️", nameAr: "سلة مهملات", nameEn: "Wastebasket", tags: ["trash", "delete", "bin"] },
    { char: "✂️", nameAr: "مقص", nameEn: "Scissors", tags: ["scissors", "cut", "craft"] },
    { char: "🪄", nameAr: "عصا سحرية", nameEn: "Magic Wand", tags: ["magic", "wand", "sparkle"] },
    { char: "🎨", nameAr: "لوحة ألوان", nameEn: "Artist Palette", tags: ["art", "paint", "color", "draw"] },
    { char: "🧠", nameAr: "دماغ", nameEn: "Brain", tags: ["brain", "think", "smart", "mind"] },
    { char: "💡", nameAr: "لمبة", nameEn: "Light Bulb", tags: ["idea", "light", "bright", "think"] },
    { char: "🔑", nameAr: "مفتاح", nameEn: "Key", tags: ["key", "unlock", "answer"] },
    { char: "🗝️", nameAr: "مفتاح قديم", nameEn: "Old Key", tags: ["key", "antique", "unlock"] },
    { char: "📋", nameAr: "قائمة", nameEn: "Clipboard", tags: ["list", "clipboard", "checklist"] },
    { char: "✅", nameAr: "تم", nameEn: "Check Mark", tags: ["check", "done", "correct", "yes"] },
    { char: "❌", nameAr: "خطأ", nameEn: "Cross Mark", tags: ["wrong", "error", "no", "delete"] },
    { char: "❓", nameAr: "سؤال", nameEn: "Question Mark", tags: ["question", "ask", "help"] },
    { char: "❗", nameAr: "تعجب", nameEn: "Exclamation", tags: ["important", "alert", "warning"] },
    { char: "💬", nameAr: "فقاعة حوار", nameEn: "Speech Bubble", tags: ["chat", "speak", "talk"] },
    { char: "💭", nameAr: "فقاعة تفكير", nameEn: "Thought Bubble", tags: ["think", "thought"] },
  ];

  const activitiesHobbies: SymDef[] = [
    { char: "⚽", nameAr: "كرة قدم", nameEn: "Soccer Ball", tags: ["soccer", "football", "sport", "ball"] },
    { char: "🏀", nameAr: "كرة سلة", nameEn: "Basketball", tags: ["basketball", "sport", "ball"] },
    { char: "🏈", nameAr: "كرة قدم أمريكية", nameEn: "Football", tags: ["football", "american", "sport"] },
    { char: "⚾", nameAr: "بيسبول", nameEn: "Baseball", tags: ["baseball", "sport", "ball"] },
    { char: "🥎", nameAr: "سوفتبول", nameEn: "Softball", tags: ["softball", "sport"] },
    { char: "🎾", nameAr: "تنس", nameEn: "Tennis", tags: ["tennis", "sport", "ball"] },
    { char: "🏐", nameAr: "كرة طائرة", nameEn: "Volleyball", tags: ["volleyball", "sport"] },
    { char: "🏉", nameAr: "رجبي", nameEn: "Rugby", tags: ["rugby", "sport"] },
    { char: "🥏", nameAr: "فريسبي", nameEn: "Disc", tags: ["frisbee", "throw"] },
    { char: "🎱", nameAr: "بلياردو", nameEn: "Pool Ball", tags: ["billiards", "pool", "8ball"] },
    { char: "🏓", nameAr: "بنغ بونغ", nameEn: "Ping Pong", tags: ["table tennis", "sport"] },
    { char: "🏸", nameAr: "ريشة", nameEn: "Badminton", tags: ["badminton", "sport"] },
    { char: "🥊", nameAr: "ملاكمة", nameEn: "Boxing Glove", tags: ["boxing", "sport", "fight"] },
    { char: "🥋", nameAr: "كاراتيه", nameEn: "Martial Arts", tags: ["martial arts", "karate", "judo"] },
    { char: "⛳", nameAr: "غولف", nameEn: "Golf", tags: ["golf", "sport"] },
    { char: "⛸️", nameAr: "تزلج", nameEn: "Ice Skating", tags: ["skating", "ice", "winter"] },
    { char: "🎿", nameAr: "تزلج ثلج", nameEn: "Skiing", tags: ["ski", "snow", "winter"] },
    { char: "🛹", nameAr: "سكيتبورد", nameEn: "Skateboard", tags: ["skateboard", "sport"] },
    { char: "🚴", nameAr: "دراجة", nameEn: "Cycling", tags: ["bicycle", "bike", "sport", "ride"] },
    { char: "🏊", nameAr: "سباحة", nameEn: "Swimming", tags: ["swim", "sport", "water"] },
    { char: "🤸", nameAr: "جمباز", nameEn: "Gymnastics", tags: ["gymnastics", "sport", "flip"] },
    { char: "🏋️", nameAr: "رفع أثقال", nameEn: "Weight Lifting", tags: ["gym", "weight", "strong"] },
    { char: "🤾", nameAr: "كرة يد", nameEn: "Handball", tags: ["handball", "sport"] },
    { char: "🏇", nameAr: "سباق خيل", nameEn: "Horse Racing", tags: ["horse", "race", "sport"] },
    { char: "🎮", nameAr: "ألعاب فيديو", nameEn: "Video Game", tags: ["game", "controller", "play", "fun"] },
    { char: "🕹️", nameAr: "عصا تحكم", nameEn: "Joystick", tags: ["game", "arcade", "play"] },
    { char: "🎲", nameAr: "نرد", nameEn: "Dice", tags: ["dice", "game", "roll", "random"] },
    { char: "🧩", nameAr: "أحجية", nameEn: "Puzzle Piece", tags: ["puzzle", "game", "solve"] },
    { char: "♟️", nameAr: "شطرنج", nameEn: "Chess Pawn", tags: ["chess", "game", "strategy"] },
    { char: "🎯", nameAr: "هدف", nameEn: "Bullseye", tags: ["target", "goal", "aim", "dart"] },
    { char: "🎪", nameAr: "سيرك", nameEn: "Circus Tent", tags: ["circus", "fun", "show"] },
    { char: "🎭", nameAr: "مسرح", nameEn: "Theater", tags: ["theater", "drama", "act", "mask"] },
    { char: "🎨", nameAr: "رسم", nameEn: "Art Palette", tags: ["art", "paint", "draw", "color"] },
    { char: "🎬", nameAr: "سينما", nameEn: "Clapper Board", tags: ["movie", "film", "cinema"] },
    { char: "🎤", nameAr: "ميكروفون", nameEn: "Microphone", tags: ["mic", "sing", "karaoke", "music"] },
    { char: "🎧", nameAr: "سماعات", nameEn: "Headphone", tags: ["music", "listen", "headphones"] },
    { char: "🎼", nameAr: "نوتة موسيقية", nameEn: "Musical Score", tags: ["music", "notes", "sheet"] },
    { char: "🎵", nameAr: "نغمة", nameEn: "Musical Note", tags: ["music", "note", "melody"] },
    { char: "🎶", nameAr: "نغمات", nameEn: "Musical Notes", tags: ["music", "notes", "melody"] },
    { char: "🥁", nameAr: "طبل", nameEn: "Drum", tags: ["drum", "music", "beat"] },
    { char: "🎹", nameAr: "بيانو", nameEn: "Piano", tags: ["piano", "music", "keys"] },
    { char: "🎸", nameAr: "غيتار", nameEn: "Guitar", tags: ["guitar", "music", "rock"] },
    { char: "🎺", nameAr: "بوق", nameEn: "Trumpet", tags: ["trumpet", "music", "brass"] },
    { char: "🎻", nameAr: "كمان", nameEn: "Violin", tags: ["violin", "music", "classical"] },
    { char: "🪘", nameAr: "دربكة", nameEn: "Long Drum", tags: ["drum", "music", "percussion"] },
    { char: "📷", nameAr: "كاميرا", nameEn: "Camera", tags: ["camera", "photo", "picture"] },
    { char: "📹", nameAr: "كاميرا فيديو", nameEn: "Video Camera", tags: ["video", "record", "film"] },
    { char: "🎥", nameAr: "كاميرا سينما", nameEn: "Movie Camera", tags: ["movie", "film", "record"] },
    { char: "🧵", nameAr: "خيط", nameEn: "Thread", tags: ["sew", "craft", "textile"] },
    { char: "🧶", nameAr: "كرة صوف", nameEn: "Yarn", tags: ["yarn", "knit", "craft"] },
    { char: "🪡", nameAr: "إبرة خياطة", nameEn: "Sewing Needle", tags: ["needle", "sew", "craft"] },
    { char: "🎣", nameAr: "صيد سمك", nameEn: "Fishing", tags: ["fish", "hobby", "outdoor"] },
    { char: "🧗", nameAr: "تسلق", nameEn: "Climbing", tags: ["climb", "sport", "adventure"] },
    { char: "🏕️", nameAr: "تخييم", nameEn: "Camping", tags: ["camp", "tent", "outdoor"] },
    { char: "🎠", nameAr: "حصان دوار", nameEn: "Carousel Horse", tags: ["carousel", "fun", "amusement"] },
    { char: "🎡", nameAr: "عجلة دوارة", nameEn: "Ferris Wheel", tags: ["ferris wheel", "amusement", "fun"] },
    { char: "🎢", nameAr: "أفعوانية", nameEn: "Roller Coaster", tags: ["rollercoaster", "speed", "fun"] },
    { char: "🏖️", nameAr: "شاطئ", nameEn: "Beach", tags: ["beach", "summer", "sand", "vacation"] },
  ];

  const rewardsAchievements: SymDef[] = [
    { char: "🏆", nameAr: "كأس", nameEn: "Trophy", tags: ["trophy", "winner", "champion", "first"] },
    { char: "🥇", nameAr: "ميدالية ذهبية", nameEn: "Gold Medal", tags: ["medal", "gold", "first", "winner"] },
    { char: "🥈", nameAr: "ميدالية فضية", nameEn: "Silver Medal", tags: ["medal", "silver", "second"] },
    { char: "🥉", nameAr: "ميدالية برونزية", nameEn: "Bronze Medal", tags: ["medal", "bronze", "third"] },
    { char: "🏅", nameAr: "ميدالية رياضية", nameEn: "Sports Medal", tags: ["medal", "sport", "achievement"] },
    { char: "🎖️", nameAr: "وسام عسكري", nameEn: "Military Medal", tags: ["medal", "honor", "brave"] },
    { char: "🎗️", nameAr: "شريط تذكاري", nameEn: "Reminder Ribbon", tags: ["ribbon", "awareness"] },
    { char: "📜", nameAr: "شهادة", nameEn: "Scroll", tags: ["certificate", "scroll", "diploma"] },
    { char: "🎓", nameAr: "تخرج", nameEn: "Graduation", tags: ["graduate", "education", "success"] },
    { char: "👑", nameAr: "تاج", nameEn: "Crown", tags: ["crown", "king", "queen", "royal", "best"] },
    { char: "💎", nameAr: "ألماسة", nameEn: "Gem Stone", tags: ["gem", "diamond", "precious", "rare"] },
    { char: "⭐", nameAr: "نجمة ذهبية", nameEn: "Star", tags: ["star", "rating", "favorite"] },
    { char: "🌟", nameAr: "نجمة متوهجة", nameEn: "Glowing Star", tags: ["star", "shine", "great"] },
    { char: "✨", nameAr: "بريق", nameEn: "Sparkles", tags: ["sparkle", "magic", "new", "special"] },
    { char: "🎉", nameAr: "احتفال", nameEn: "Party Popper", tags: ["party", "celebrate", "congratulations"] },
    { char: "🎊", nameAr: "كونفيتي", nameEn: "Confetti Ball", tags: ["confetti", "celebrate", "party"] },
    { char: "🎈", nameAr: "بالون", nameEn: "Balloon", tags: ["balloon", "party", "birthday"] },
    { char: "🎁", nameAr: "هدية", nameEn: "Gift", tags: ["gift", "present", "birthday", "reward"] },
    { char: "🎀", nameAr: "شريط هدية", nameEn: "Ribbon", tags: ["ribbon", "gift", "bow"] },
    { char: "🪅", nameAr: "بينياتا", nameEn: "Piñata", tags: ["pinata", "party", "fun"] },
    { char: "🏁", nameAr: "علم نهاية", nameEn: "Checkered Flag", tags: ["finish", "race", "end", "winner"] },
    { char: "🚀", nameAr: "صاروخ", nameEn: "Rocket", tags: ["rocket", "fast", "launch", "space", "success"] },
    { char: "💥", nameAr: "انفجار", nameEn: "Boom", tags: ["explosion", "wow", "impact", "boom"] },
    { char: "🔥", nameAr: "نار", nameEn: "Fire", tags: ["fire", "hot", "trending", "streak"] },
    { char: "⚡", nameAr: "برق", nameEn: "Lightning", tags: ["lightning", "power", "energy", "fast"] },
    { char: "💪", nameAr: "قوة", nameEn: "Strong", tags: ["strong", "muscle", "power", "effort"] },
    { char: "🙌", nameAr: "يدين مرفوعة", nameEn: "Raised Hands", tags: ["celebration", "hooray"] },
    { char: "👏", nameAr: "تصفيق", nameEn: "Clapping Hands", tags: ["clap", "bravo", "applause"] },
    { char: "🤝", nameAr: "مصافحة", nameEn: "Handshake", tags: ["handshake", "deal", "teamwork"] },
    { char: "🫡", nameAr: "تحية عسكرية", nameEn: "Salute", tags: ["salute", "respect", "honor"] },
    { char: "🎂", nameAr: "كعكة عيد", nameEn: "Birthday Cake", tags: ["cake", "birthday", "celebrate"] },
    { char: "🍰", nameAr: "قطعة كيك", nameEn: "Cake Slice", tags: ["cake", "dessert", "sweet"] },
    { char: "🍭", nameAr: "مصاصة", nameEn: "Lollipop", tags: ["candy", "sweet", "treat"] },
    { char: "🍬", nameAr: "حلوى", nameEn: "Candy", tags: ["candy", "sweet", "treat"] },
    { char: "🍫", nameAr: "شوكولاتة", nameEn: "Chocolate", tags: ["chocolate", "sweet"] },
    { char: "🧁", nameAr: "كب كيك", nameEn: "Cupcake", tags: ["cupcake", "sweet", "treat"] },
    { char: "🎵", nameAr: "نغمة نصر", nameEn: "Victory Note", tags: ["music", "win", "victory"] },
    { char: "🦸", nameAr: "بطل خارق", nameEn: "Superhero", tags: ["hero", "super", "power", "brave"] },
    { char: "💰", nameAr: "كيس مال", nameEn: "Money Bag", tags: ["money", "reward", "rich", "coins"] },
    { char: "🪙", nameAr: "عملة", nameEn: "Coin", tags: ["coin", "money", "gold", "reward"] },
    { char: "💵", nameAr: "نقود", nameEn: "Dollar", tags: ["money", "cash", "bills"] },
    { char: "🎶", nameAr: "موسيقى احتفال", nameEn: "Celebration Music", tags: ["music", "celebrate"] },
    { char: "🌈", nameAr: "قوس قزح", nameEn: "Rainbow", tags: ["rainbow", "beautiful", "hope"] },
    { char: "🔓", nameAr: "مفتوح", nameEn: "Unlocked", tags: ["unlock", "open", "achieve"] },
    { char: "📊", nameAr: "إحصائيات", nameEn: "Statistics", tags: ["stats", "progress", "chart"] },
    { char: "📈", nameAr: "نمو", nameEn: "Growth", tags: ["progress", "up", "improve"] },
    { char: "🎯", nameAr: "هدف محقق", nameEn: "Target Hit", tags: ["goal", "target", "achieve"] },
    { char: "✅", nameAr: "مكتمل", nameEn: "Complete", tags: ["done", "check", "complete", "correct"] },
    { char: "💯", nameAr: "درجة كاملة", nameEn: "Perfect Score", tags: ["perfect", "100", "score"] },
    { char: "🏠", nameAr: "بيت", nameEn: "House", tags: ["house", "home"] },
  ];

  const projectSpecific: SymDef[] = [
    { char: "📝", nameAr: "مهمة", nameEn: "Task", tags: ["task", "homework", "assignment"] },
    { char: "✏️", nameAr: "إجابة", nameEn: "Answer", tags: ["answer", "write", "response"] },
    { char: "❓", nameAr: "سؤال", nameEn: "Question", tags: ["question", "quiz", "ask"] },
    { char: "💡", nameAr: "فكرة", nameEn: "Idea", tags: ["idea", "hint", "tip"] },
    { char: "⏱️", nameAr: "وقت", nameEn: "Timer", tags: ["time", "countdown", "speed"] },
    { char: "📊", nameAr: "تقرير", nameEn: "Report", tags: ["report", "grade", "score"] },
    { char: "🎯", nameAr: "هدف يومي", nameEn: "Daily Goal", tags: ["goal", "daily", "target"] },
    { char: "🏅", nameAr: "وسام", nameEn: "Badge", tags: ["badge", "achievement", "reward"] },
    { char: "⭐", nameAr: "نجمة تقييم", nameEn: "Rating Star", tags: ["rating", "star", "evaluate"] },
    { char: "🔔", nameAr: "تنبيه", nameEn: "Notification", tags: ["notification", "alert", "bell"] },
    { char: "📚", nameAr: "مكتبة المهام", nameEn: "Task Library", tags: ["library", "tasks", "collection"] },
    { char: "👨‍👩‍👧‍👦", nameAr: "عائلة", nameEn: "Family", tags: ["family", "parent", "child"] },
    { char: "👦", nameAr: "ولد", nameEn: "Boy", tags: ["boy", "child", "kid", "son"] },
    { char: "👧", nameAr: "بنت", nameEn: "Girl", tags: ["girl", "child", "kid", "daughter"] },
    { char: "👨", nameAr: "أب", nameEn: "Father", tags: ["father", "dad", "parent", "man"] },
    { char: "👩", nameAr: "أم", nameEn: "Mother", tags: ["mother", "mom", "parent", "woman"] },
    { char: "🧑‍🏫", nameAr: "معلم", nameEn: "Teacher", tags: ["teacher", "educator"] },
    { char: "🏫", nameAr: "مدرسة", nameEn: "School", tags: ["school", "building"] },
    { char: "📖", nameAr: "درس", nameEn: "Lesson", tags: ["lesson", "study", "learn"] },
    { char: "🧪", nameAr: "اختبار", nameEn: "Test", tags: ["test", "exam", "quiz"] },
    { char: "📋", nameAr: "قائمة مهام", nameEn: "Task List", tags: ["list", "tasks", "checklist"] },
    { char: "🗓️", nameAr: "جدول", nameEn: "Calendar", tags: ["calendar", "schedule", "date"] },
    { char: "📅", nameAr: "موعد", nameEn: "Calendar Day", tags: ["date", "appointment", "deadline"] },
    { char: "🔁", nameAr: "تكرار", nameEn: "Repeat", tags: ["repeat", "loop", "again"] },
    { char: "📤", nameAr: "إرسال", nameEn: "Send", tags: ["send", "upload", "submit"] },
    { char: "📥", nameAr: "استلام", nameEn: "Receive", tags: ["receive", "download", "inbox"] },
    { char: "🔒", nameAr: "مقفل", nameEn: "Locked", tags: ["lock", "secure", "private"] },
    { char: "🔓", nameAr: "مفتوح", nameEn: "Unlocked", tags: ["unlock", "open", "access"] },
    { char: "⚙️", nameAr: "إعدادات", nameEn: "Settings", tags: ["settings", "gear", "config"] },
    { char: "🛡️", nameAr: "حماية", nameEn: "Shield", tags: ["shield", "protect", "safe"] },
    { char: "💬", nameAr: "محادثة", nameEn: "Chat", tags: ["chat", "message", "talk"] },
    { char: "🔗", nameAr: "رابط", nameEn: "Link", tags: ["link", "connect", "url"] },
    { char: "📌", nameAr: "تثبيت", nameEn: "Pin", tags: ["pin", "important", "save"] },
    { char: "🏠", nameAr: "الرئيسية", nameEn: "Home", tags: ["home", "main", "dashboard"] },
    { char: "👤", nameAr: "حساب", nameEn: "Account", tags: ["account", "profile", "user"] },
    { char: "🎮", nameAr: "ألعاب تعليمية", nameEn: "Educational Games", tags: ["game", "learn", "play"] },
    { char: "🛒", nameAr: "متجر", nameEn: "Store", tags: ["store", "shop", "buy"] },
    { char: "💳", nameAr: "دفع", nameEn: "Payment", tags: ["payment", "card", "buy"] },
    { char: "👁️", nameAr: "مراقبة", nameEn: "Watch", tags: ["watch", "monitor", "see", "parental"] },
    { char: "📲", nameAr: "تطبيق", nameEn: "App", tags: ["app", "mobile", "phone"] },
    { char: "🌐", nameAr: "إنترنت", nameEn: "Internet", tags: ["internet", "web", "online"] },
    { char: "🔊", nameAr: "صوت", nameEn: "Sound", tags: ["sound", "audio", "volume"] },
    { char: "🔇", nameAr: "صامت", nameEn: "Mute", tags: ["mute", "silent", "quiet"] },
    { char: "📶", nameAr: "اتصال", nameEn: "Signal", tags: ["signal", "wifi", "connection"] },
    { char: "🌙", nameAr: "وضع ليلي", nameEn: "Night Mode", tags: ["night", "dark", "moon", "sleep"] },
    { char: "☀️", nameAr: "وضع نهاري", nameEn: "Day Mode", tags: ["day", "light", "sun"] },
  ];

  // Combine all symbols
  const allSymbols: { cat: string; data: SymDef[] }[] = [
    { cat: "numbers-letters", data: numbersLetters },
    { cat: "emotions-faces", data: emotionsFaces },
    { cat: "animals", data: animals },
    { cat: "nature-elements", data: natureElements },
    { cat: "shapes-colors", data: shapesColors },
    { cat: "educational-tools", data: educationalTools },
    { cat: "activities-hobbies", data: activitiesHobbies },
    { cat: "rewards-achievements", data: rewardsAchievements },
    { cat: "project-specific", data: projectSpecific },
  ];

  let totalInserted = 0;

  for (const group of allSymbols) {
    const categoryId = catMap[group.cat];
    if (!categoryId) {
      console.error(`  ❌ Category "${group.cat}" not found`);
      continue;
    }

    // Check if already seeded for this category
    const existingCount = await db.select({ count: sql<number>`count(*)::int` })
      .from(librarySymbols).where(eq(librarySymbols.categoryId, categoryId));
    
    if ((existingCount[0]?.count || 0) >= group.data.length) {
      console.log(`  ⏭️  Category "${group.cat}" already has ${existingCount[0]?.count} symbols (expected ${group.data.length})`);
      totalInserted += existingCount[0]?.count || 0;
      continue;
    }

    console.log(`  📦 Inserting ${group.data.length} symbols for "${group.cat}"...`);
    
    const values = group.data.map((s, i) => ({
      categoryId,
      char: s.char,
      nameAr: s.nameAr,
      nameEn: s.nameEn,
      tags: s.tags,
      price: 0,
      isPremium: false,
      sortOrder: i,
    }));

    // Batch insert in chunks of 100
    for (let i = 0; i < values.length; i += 100) {
      const chunk = values.slice(i, i + 100);
      const result = await db.insert(librarySymbols).values(chunk).returning({ id: librarySymbols.id });
      totalInserted += result.length;
    }
    
    console.log(`  ✅ Inserted ${group.data.length} symbols for "${group.cat}"`);
  }

  console.log(`\n🎉 Total: ${totalInserted} symbols across ${categories.length} categories`);
  
  await pool.end();
  process.exit(0);
}

seedSymbols().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
